### ISSUE TITLE
Dear PyGui Showcase

### ISSUE THREAD

**Issue by bandit-masked** [Glouwhy/Wordle.py#1]
I just wanted to reach out and let you know that I have added your Wordle clone to the Dear PyGui showcase on GitHub. Just for the fun of it, I made a new GIF.

https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase#wordle-clone

**Comment by j-zunino** [comment]
Hi, thanks for reaching out and for featuring my Wordle clone in the Dear PyGui showcase ^^
